SEED: 42
PROJECT_NAME: "3D-CT-Diffusion-Unet-testtraining"
EPOCHS: 30
BATCH_SIZE: 1
VALIDATION_SPLIT: 0.2
MAX_GRAD_NORM: 1.0
NUM_WORKERS: 8

DATA:
  PT_DATA_DIR: "/workspace/data/LIDC/dataset_256/CT_pt"
  DRR_DIR: "/workspace/data/LIDC/dataset_256/DRR_mod"

TRAINING:
  ENCODER: "convnext"  # 使用するエンコーダー (resnet, convnext, efficientnet)
  PATCH_SIZE: 160
  LOSS_PHASE_EPOCHS: [10, 20]

OPTUNA:
  N_TRIALS: 20
  PARAMS:
    l1_ssim_ratio: [0.3, 0.7]
    lr: [1.0e-5, 5.0e-4]
    weight_decay: [1.0e-6, 1.0e-2]
    gradient_accumulation_steps: [1, 2, 4, 8]